apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  restartPolicy: Never
  containers:
  - name: client
    tty: true
    image: python:3.10-slim-bookworm
    command: ["/bin/bash"]
    imagePullPolicy: Always
    resources:
      limits:
        memory: "16G"
        cpu: "4"