apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  labels:
    app: vllm
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: vllm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
  labels:
    app: vllm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels: 
        app: vllm
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Equal
        value: "gpu"
        key: "nodetype"
      nodeSelector:
        nodetype: gpu
        gpuspecs: V100_32GB
      containers:
      - name: vllm
        image: vllm/vllm-openai
        env:
        - name: HF_HOME
          value: "/network/rshaw/hf_cache"
        args: ["--model", "HuggingFaceH4/zephyr-7b-beta", "--tensor-parallel-size", "1", "--dtype", "float16", "--enforce-eager", "--disable-log-requests"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "16G"
            cpu: "4"
            nvidia.com/gpu: 1
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: shared-network-drive
          mountPath: "/network"
        - name: dshm 
          mountPath: "/dev/shm"
      volumes:
      - name: shared-network-drive
        nfs: 
          server: storage-gateway.wisp.internal.neuralmagic.com
          path: /on-prem-storage-gw
      - name: dshm 
        emptyDir:
          medium: Memory

