apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  labels:
    app: vllm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: vllm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
  labels:
    app: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels: 
        app: vllm
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Equal
        value: 1
        key: "nvidia.com/count"
      nodeSelector:
        nvidia.com/count: 1
      containers:
      - name: vllm
        image: ubuntu
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: hf-token
        imagePullPolicy: Always
        resources:
          limits:
            memory: "16G"
            cpu: "4"
            nvidia.com/gpu: 1
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: dshm 
          mountPath: "/dev/shm"
      volumes:
      - name: dshm 
        emptyDir:
          medium: Memory
