apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-pvc
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: downloader-pvc-snapshot
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: premium-rwo
