apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: tinyllama
spec:
  predictor:
    model:
      runtime: nm-vllm
      modelFormat:
        name: huggingface
      storageUri: "oci://robertgouldshaw2/tinyllama:1.0"
