apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: nm-vllm
spec:
  supportedModelFormats:
    - name: huggingface
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: vllm/vllm-openai
      ports:
        - containerPort: 8000
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          cpu: 4
          memory: 16Gi
          nvidia.com/gpu: 1
  disabled: false
  multiModel: false
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: nm-vllm
spec:
  predictor:
    model:
      runtime: nm-vllm
      modelFormat:
        name: huggingface
      storage:
        key: gcs
        path: models/TinyLlama/TinyLlama-1.1B-Chat-v1.0
        parameters:
          bucket: nm-vllm-models