apiVersion: v1
kind: Namespace
metadata:
  name: vllm-example
  labels:
    name: vllm-example
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: vllm-example
  labels:
    app: vllm
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: vllm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
  namespace: vllm-example
  labels:
    app: vllm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels: 
        app: vllm
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      containers:
      - name: vllm
        image: vllm/vllm-openai
        args: ["--model", "HuggingFaceH4/zephyr-7b-beta", "--tensor-parallel-size", "2", "--dtype", "float16", "--enforce-eager", "--disable-log-requests"]
        resources:
          limits:
            nvidia.com/gpu: 2
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: dshm 
          mountPath: "/dev/shm"
      volumes:
      - name: dshm 
        emptyDir:
          medium: Memory
